version: "2"

services:
  web:
    image: greggu/tatz:0.0.1
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web
    networks:
      tatz:
        aliases:
          - web
    ports:
      - 8080:8080

networks:
  tatz:
